
#ifndef _MEMORY_MAP_OFFSETS_
#define _MEMORY_MAP_OFFSETS_

#define MEMORY_ADDR_TABLE 0x00
#define MEMORY_READ_TABLE 0x40
#define MEMORY_WRITE_TABLE 0x80
#define MEMORY_CART_WRITE 0xC0
#define MEMORY_CART_READ 0xC4
#define MEMORY_BANK_SWITCHING 0xC8
#define MEMORY_MISC_START 0xD0
#define MEMORY_MISC_RAM_BANK 0x178
#define MEMORY_MISC_TIMER 0x180
#define MEMORY_RAM_START 0x2D0
#define MEMORY_ROM 0x82D4
#define MEMORY_CART_RAM 0x82D8
#define MEMORY_VRAM 0x82D8
#define MEMORY_BG_PAL 0xC2D8
#define MEMORY_OBJ_PAL 0xC318

#endif